// This file was automatically generated by the Dapper.SimpleCRUD T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `TyrionBankerDB`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=localhost;Initial Catalog=TyrionBankerDB;User Id=tyrionbanker;Password=tyrionbanker`
//     Include Views:          `True`

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace TyrionBanker.Infrastructure.Models
{
	/// <summary>
	/// A class which represents the UserInfo table.
	/// </summary>
	[Table("UserInfo")]
	public partial class UserInfo
	{
		[Key]
		public virtual int UserId { get; set; }
		public virtual string Name { get; set; }
		public virtual string Password { get; set; }
		public virtual IEnumerable<UserRole> UserRole { get; set; }
	}

	/// <summary>
	/// A class which represents the BankAccountTypes table.
	/// </summary>
	[Table("BankAccountTypes")]
	public partial class BankAccountType
	{
		[Key]
		public virtual int BankAccountTypeId { get; set; }
		public virtual string Name { get; set; }
		public virtual IEnumerable<BankAccount> BankAccount { get; set; }
	}

	/// <summary>
	/// A class which represents the BankAccount table.
	/// </summary>
	[Table("BankAccount")]
	public partial class BankAccount
	{
		[Key]
		public virtual int BankAccountId { get; set; }
		public virtual string BankAccountNo { get; set; }
		public virtual decimal Balanca { get; set; }
		public virtual int BankAccountTypeId { get; set; }
		public virtual BankAccountType BankAccountType { get; set; }
	}

	/// <summary>
	/// A class which represents the Roles table.
	/// </summary>
	[Table("Roles")]
	public partial class Role
	{
		[Key]
		public virtual int RoleId { get; set; }
		public virtual string Name { get; set; }
		public virtual IEnumerable<RolePrivilage> RolePrivilage { get; set; }
		public virtual IEnumerable<UserRole> UserRole { get; set; }
	}

	/// <summary>
	/// A class which represents the Privilages table.
	/// </summary>
	[Table("Privilages")]
	public partial class Privilage
	{
		[Key]
		public virtual int PrivilageId { get; set; }
		public virtual string Name { get; set; }
		public virtual IEnumerable<RolePrivilage> RolePrivilage { get; set; }
	}

	/// <summary>
	/// A class which represents the RolePrivilage table.
	/// </summary>
	[Table("RolePrivilage")]
	public partial class RolePrivilage
	{
		[Key]
		public virtual int RolePrivilageId { get; set; }
		public virtual int RoleId { get; set; }
		public virtual int PrivilageId { get; set; }
		public virtual Role Role { get; set; }
		public virtual Privilage Privilage { get; set; }
	}

	/// <summary>
	/// A class which represents the UserRole table.
	/// </summary>
	[Table("UserRole")]
	public partial class UserRole
	{
		[Key]
		public virtual int UserRoleId { get; set; }
		public virtual int UserId { get; set; }
		public virtual int RoleId { get; set; }
		public virtual UserInfo UserInfo { get; set; }
		public virtual Role Role { get; set; }
	}

}
